### ISSUE TITLE
Create the Code of Conduct

### ISSUE THREAD

**Issue by arianerocha** [sumelms/website#2]
Discuss and adopt a code of conduct to define Sumé community standards.
We can describe on the website and link with every Sumé application.

**Comment by rluders** [comment]
I guess that we need some examples or at least starters, so I'm dropping some interesting links here:

- https://miloslav.website/code-of-conduct/
- https://opensource.guide/code-of-conduct/
- https://i-sight.com/resources/18-of-the-best-code-of-conduct-examples/
